name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
  
      - name: Build Flutter App per ABI
        run:  |
          flutter build apk --split-per-abi
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk linux-mon-arm64-v8a-master.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk linux-mon-armeabiv7a-master.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk linux-mon-x86-64-master.apk
          flutter clean
          
      - name: Build Flutter App as Single Package
        run: |
          flutter build apk
          cp build/app/outputs/flutter-apk/app-release.apk linux-mon-universal-master.apk
          flutter clean
          ls
      
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Master Builds"
          files: |
            linux-mon-arm64-v8a-master.apk
            linux-mon-armeabiv7a-master.apk
            linux-mon-x86-64-master.apk
            linux-mon-universal-master.apk
